spring:
  port: 8080
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/fileDB
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
#logging:
#  level:
#    level:
#      root: info
#    com:
#      danawa: info
#  file:
#    path: /var/log
#    max-history: 30
#    max-size: 500MB
logging:
  config: classpath:log4j2-dev.xml
dsearch:
  notice:
    telegram:
      enabled: ${DSEARCH_NOTICE_TELEGRAM_ENABLED:'false'}
      bot: ${DSEARCH_NOTICE_TELEGRAM_BOT:''}
      chat: ${DSEARCH_NOTICE_TELEGRAM_CHAT:''}
  auth:
    secret: dsearch-secret
    expiration-time-millis: 7200000
  delete: .dsearch*
  admin:
    username: admin
    password: admin
    email: admin@example.com
  dictionary:
    apply: .dsearch_dict_apply
    setting: .dsearch_dict_setting
    index: .dsearch_dict
#    index: .dsearch_dictionary
  reference:
    index: .dsearch_reference
  collection:
    index: .dsearch_collection
    index-suffix-a: -a
    index-suffix-b: -b
    params:
      encoding: utf-8
      bulkSize: 500
      reset: true
      threadSize: 1
    indexing:
      "[index.routing.allocation.include.role]": index
      "[index.routing.allocation.exclude.role]": null
      "[index.number_of_replicas]": 1
      refresh_interval: "-1"
    propagate:
      "[index.routing.allocation.include.role]": null
      "[index.routing.allocation.exclude.role]": index
      "[index.number_of_replicas]": 1
      refresh_interval: "1s"
  jdbc:
    setting: .dsearch_jdbc
  build:
    name: @project.name@
    version: @project.version@
  timeout: 43200000
  comments:
    setting: .dsearch_mapping_comments