
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~\dsearchDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    level:
      root: info
    com:
      danawa: debug
  file:
    path: C:\\windows\\temp
    max-history: 7
    clean-history-on-start: true
    max-size: 100MB
dsearch:
  auth:
    secret: dsearch-secret
    expiration-time-millis: 7200000
  delete: .dsearch*
  admin:
    username: admin
    password: admin
    email: admin@example.com
  dictionary:
    setting: .dsearch_dict_setting
    index: .dsearch_dict
#    index: .dsearch_dictionary
  reference:
    index: .dsearch_reference
  collection:
    index: .dsearch_collection
    index-suffix-a: -a
    index-suffix-b: -b
    params:
      encoding: utf-8
      bulkSize: 100
      reset: true
      threadSize: 1
    indexing:
      "[index.routing.allocation.include.role]": index
      "[index.routing.allocation.exclude.role]": null
      "[index.number_of_replicas]": 0
      refresh_interval: "-1"
    propagate:
      "[index.routing.allocation.include.role]": null
      "[index.routing.allocation.exclude.role]": index
      "[index.number_of_replicas]": 1
      refresh_interval: "1s"
  jdbc:
    setting: .dsearch_jdbc
  build:
    name: @project.name@
    version: @project.version@
