server:
  port: 8080
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~\dsearchDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
#logging:
#  level:
#    level:
#      root: info
#    com:
#      danawa: info
#  file:
#    path: C:\\windows\\temp
#    max-history: 7
#    clean-history-on-start: true
#    max-size: 100MB
#logging:
#  config: classpath:log4j2.xml
dsearch:
  notice:
    telegram:
      enabled: ${DSEARCH_NOTICE_TELEGRAM_ENABLED:'false'}
      bot: ${DSEARCH_NOTICE_TELEGRAM_BOT:''}
      chat: ${DSEARCH_NOTICE_TELEGRAM_CHAT:''}
  auth:
    secret: dsearch-secret
    expiration-time-millis: 7200000
  delete: .dsearch*
  admin:
    username: admin
    password: admin
    email: admin@example.com
  dictionary:
    apply: .dsearch_dict_apply
    setting: .dsearch_dict_setting
    index: .dsearch_dict
#    index: .dsearch_dictionary
  reference:
    index: .dsearch_reference
  collection:
    index: .dsearch_collection
    index-suffix-a: -a
    index-suffix-b: -b
    params:
      encoding: utf-8
      bulkSize: 100
      reset: true
      threadSize: 1
    indexing:
      refresh_interval: "-1"
    propagate:
      refresh_interval: "1s"
  jdbc:
    setting: .dsearch_jdbc
  build:
    name: asdf
    version: asdf
#  timeout: 28800000
  timeout: 43200000
  comments:
    setting: .dsearch_mapping_comments
